local M = {
	light = {
		vertical = "│",
		horizontal = "─",
		vertical_left = "├",
		vertical_right = "┤",
		horizontal_down = "┬",
		horizontal_up = "┴",
		top_left = "┌",
		top_right = "┐",
		bottom_left = "└",
		bottom_right = "┘",
		cross = "┼",
	},
	heavy = {
		vertical = "┃",
		horizontal = "━",
		vertical_left = "┣",
		vertical_right = "┫",
		horizontal_down = "┳",
		horizontal_up = "┻",
		top_left = "┏",
		top_right = "┓",
		bottom_left = "┗",
		bottom_right = "┛",
		cross = "╋",
	},
	double = {
		vertical = "║",
		horizontal = "═",
		vertical_left = "╠",
		vertical_right = "╣",
		horizontal_down = "╦",
		horizontal_up = "╩",
		top_left = "╔",
		top_right = "╗",
		bottom_left = "╚",
		bottom_right = "╝",
		cross = "╬",
	},
	["double-dash"] = {
		vertical = "╎",
		horizontal = "╌",
		vertical_left = "╟",
		vertical_right = "╢",
		horizontal_down = "╤",
		horizontal_up = "╧",
		top_left = "┌",
		top_right = "┐",
		bottom_left = "└",
		bottom_right = "┘",
		cross = "┼",
	},
	["triple-dash"] = {
		vertical = "┆",
		horizontal = "┄",
		vertical_left = "┝",
		vertical_right = "┥",
		horizontal_down = "┰",
		horizontal_up = "┸",
		top_left = "┌",
		top_right = "┐",
		bottom_left = "└",
		bottom_right = "┘",
		cross = "┼",
	},
	["quadruple-dash"] = {
		vertical = "┊",
		horizontal = "┈",
		vertical_left = "┝",
		vertical_right = "┥",
		horizontal_down = "┰",
		horizontal_up = "┸",
		top_left = "┌",
		top_right = "┐",
		bottom_left = "└",
		bottom_right = "┘",
		cross = "┼",
	},
}

return M
